# Redis Alerting Rules
# Reglas de alertas para Redis

groups:
  - name: redis
    rules:
      # Redis Down
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis instance {{ $labels.instance }} has been down for more than 1 minute."

      # Redis High Memory Usage
      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Redis high memory usage"
          description: "Redis instance {{ $labels.instance }} has {{ $value }}% memory usage."

      # Redis High CPU Usage
      - alert: RedisHighCPUUsage
        expr: rate(redis_cpu_sys_seconds_total[5m]) > 0.8
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Redis high CPU usage"
          description: "Redis instance {{ $labels.instance }} has high CPU usage."

      # Redis Slow Commands
      - alert: RedisSlowCommands
        expr: rate(redis_slowlog_length[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Redis slow commands"
          description: "Redis instance {{ $labels.instance }} has slow commands."

      # Redis High Connection Count
      - alert: RedisHighConnections
        expr: redis_connected_clients > 100
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Redis high connection count"
          description: "Redis instance {{ $labels.instance }} has {{ $value }} connections."
